version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: setsunaexia/gocomers-test
    container_name: go_container
    env_file:
      - .env
    tty: true
    ports:
      - '6626:6625'
    restart: on-failure

    networks:
      - bridge

# Networks to be created to facilitate communication between containers
networks:
  bridge:
    driver: bridge